name = "telephone-ai-twitter-bot"

main = "index.js"
workers_dev = true
compatibility_date = "2022-07-26"
node_compat = true

[triggers]
# workers can have at most 3 triggers
crons = ["0 * * * *", "20 * * * *", "40 * * * *"]